# AA241x local data

float32 N				# local North coordinate (from center of lake)
float32 E				# local East coordinate (from center of lake)
float32 D_baro			# local Down coordinate (from center of lake) using barometer
float32 D_gps			# local Down coordinate (from center of lake) using gps
float32 body_u			# Body u velocity
float32 body_v			# Body v velocity
float32 body_w			# Body w velocity
float32 ground_speed	# the ground speed in m/s